### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by PsyShark** [normanvolt/blockchain-parser#1]
Win10x64, python 3.4, in the blockchain-parser.py file, changed the blk location lines to its own. When you run the project, you get an error

**> python blockchain-parser.py
  File 'blockchain-parser.py', line 22
    if (L % 2) <> 0:
                ^
SyntaxError: invalid syntax**

How to beat this error?

**Comment by normanvolt** [comment]
The code s been tested in Python 2.7 only, sorry

**Comment by PsyShark** [comment]
On Python 2.7 works.
What to do with * .hash files?
For each * .blk it creates a file of about 350 Mb.
After stopping the program starts to re-run the blockchain. How to beat it?

**Comment by normanvolt** [comment]
> What to do with * .hash files?
It is the parsing results, open them in any text reader
> After stopping the program starts to re-run the blockchain
I don't understand what do you mean
