### ISSUE TITLE
SyntaxError: invalid syntax in line 22

### ISSUE THREAD

**Issue by Reimelt** [normanvolt/blockchain-parser#2]
I am using python 3.6.6 and arch Linux.

File "blockchain-parser.py", line 22
    if (L % 2) <> 0:
                ^
SyntaxError: invalid syntax

**Comment by PsyShark** [comment]
> I am using python 3.6.6 and arch Linux.
> 
> File "blockchain-parser.py", line 22
> if (L % 2) <> 0:
> ^
> SyntaxError: invalid syntax

Program only for Python 2.7

**Comment by normanvolt** [comment]
I made some changes. Now it compatible with Python 3.x also.
